import { useState } from "react";
import { deleteMeeting } from "../api/client";

/* ── Status badge config ──────────────────────────────────── */
const STATUS = {
  pending:      { label: "Queued",       bg: "bg-slate-100",   text: "text-slate-500",  dot: "bg-slate-400",                   icon: "⏳" },
  transcribing: { label: "Transcribing", bg: "bg-blue-50",     text: "text-blue-600",   dot: "bg-blue-500 animate-pulse",      icon: "🎙️" },
  summarizing:  { label: "Summarizing",  bg: "bg-amber-50",    text: "text-amber-600",  dot: "bg-amber-500 animate-pulse",     icon: "🤖" },
  done:         { label: "Completed",    bg: "bg-emerald-50",  text: "text-emerald-700",dot: "bg-emerald-500",                 icon: "✅" },
  error:        { label: "Error",        bg: "bg-red-50",      text: "text-red-600",    dot: "bg-red-500",                    icon: "❌" },
};

/* ── PDF export (no external library) ───────────────────────
   Builds a styled HTML document, opens in a new tab, prints it.
   User uses browser "Save as PDF" in the print dialog.           */
function downloadPdf(meeting) {
  const fmt = (iso) => new Date(iso).toLocaleString("en-IN", {
    dateStyle: "long", timeStyle: "short",
  });

  const listHtml = (items, numbered = false) =>
    items.length === 0
      ? "<p style='color:#94a3b8;font-style:italic'>None recorded.</p>"
      : `<ol style='padding-left:1.4em;margin:0;${numbered ? "" : "list-style:none;padding-left:0"}'>
           ${items.map((it, i) => `
             <li style='margin-bottom:8px;display:flex;gap:10px;align-items:flex-start'>
               <span style='background:#7c3aed;color:#fff;border-radius:50%;
                 min-width:22px;height:22px;display:inline-flex;align-items:center;
                 justify-content:center;font-size:11px;font-weight:700;margin-top:1px'>${i+1}</span>
               <span style='flex:1;color:#334155'>${it}</span>
             </li>`).join("")}
         </ol>`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Meeting Summary — ${meeting.filename}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Inter, system-ui, sans-serif; background: #fff; color: #1e293b;
         padding: 48px; max-width: 800px; margin: 0 auto; }
  .header { border-bottom: 3px solid #7c3aed; padding-bottom: 24px; margin-bottom: 32px; }
  .logo   { font-size: 13px; color: #7c3aed; font-weight: 600; letter-spacing:.05em;
            text-transform:uppercase; margin-bottom: 12px; }
  h1      { font-size: 22px; font-weight: 700; color: #1e293b; margin-bottom: 6px; }
  .meta   { font-size: 13px; color: #94a3b8; }
  .section { margin-bottom: 28px; }
  .section-title {
    font-size: 11px; font-weight: 700; letter-spacing: .08em;
    text-transform: uppercase; color: #7c3aed;
    margin-bottom: 10px; padding-bottom: 6px;
    border-bottom: 1px solid #ede9fe;
  }
  .summary-text { font-size: 15px; line-height: 1.7; color: #334155; }
  .transcript-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px;
    padding: 16px; font-size: 13px; line-height: 1.7; color: #64748b;
    white-space: pre-wrap; max-height: none; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0;
    font-size: 11px; color: #cbd5e1; text-align: center; }
  @media print {
    body { padding: 32px; }
    .no-print { display: none; }
  }
</style>
</head>
<body>
  <div class="header">
    <div class="logo">🎙️ Meeting Summarizer</div>
    <h1>${meeting.filename}</h1>
    <div class="meta">${meeting.created_at ? fmt(meeting.created_at) : ""}</div>
  </div>

  <div class="section">
    <div class="section-title">📋 Summary</div>
    <p class="summary-text">${meeting.summary || "No summary available."}</p>
  </div>

  <div class="section">
    <div class="section-title">✅ Key Decisions</div>
    ${listHtml(meeting.key_decisions || [])}
  </div>

  <div class="section">
    <div class="section-title">📌 Action Items</div>
    ${listHtml(meeting.action_items || [], true)}
  </div>

  ${meeting.transcript ? `
  <div class="section">
    <div class="section-title">📄 Full Transcript</div>
    <div class="transcript-box">${meeting.transcript}</div>
  </div>` : ""}

  <div class="footer">Generated by Meeting Summarizer · Powered by Groq Whisper + Qwen AI</div>

  <script>window.onload = () => { window.print(); }<\/script>
</body>
</html>`;

  const win = window.open("", "_blank");
  win.document.write(html);
  win.document.close();
}

/* ── Sub-components ─────────────────────────────────────── */
function StatusBadge({ status }) {
  const s = STATUS[status] || STATUS.pending;
  return (
    <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold ${s.bg} ${s.text}`}>
      <span className={`w-1.5 h-1.5 rounded-full flex-shrink-0 ${s.dot}`} />
      {s.label}
    </span>
  );
}

function SectionBlock({ title, icon, colorClass, children }) {
  return (
    <div className={`rounded-xl p-4 ${colorClass}`}>
      <h4 className="text-xs font-bold tracking-widest uppercase text-slate-400 mb-3 flex items-center gap-1.5">
        <span>{icon}</span>{title}
      </h4>
      {children}
    </div>
  );
}

function ItemList({ items, variant = "decision" }) {
  if (!items || items.length === 0)
    return <p className="text-sm text-slate-400 italic">None recorded.</p>;

  const dotColors = {
    decision: "bg-indigo-600 text-white",
    action:   "bg-violet-600 text-white",
  };

  return (
    <ul className="space-y-2">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2.5">
          <span className={`mt-0.5 w-5 h-5 flex-shrink-0 rounded-full flex items-center justify-center text-[10px] font-bold ${dotColors[variant]}`}>
            {i + 1}
          </span>
          <span className="text-sm text-slate-600 leading-relaxed flex-1">{item}</span>
        </li>
      ))}
    </ul>
  );
}

function ProcessingBar({ status }) {
  const steps = [
    { key: "pending",      label: "Queued",       done: false },
    { key: "transcribing", label: "Transcribing",  done: false },
    { key: "summarizing",  label: "Summarizing",   done: false },
    { key: "done",         label: "Completed",     done: true  },
  ];
  const currentIdx = steps.findIndex(s => s.key === status);

  return (
    <div className="px-5 py-4 border-t border-slate-100">
      <div className="flex items-center gap-2 mb-3">
        <div className="w-4 h-4 border-2 border-violet-300 border-t-violet-600 rounded-full animate-spin flex-shrink-0" />
        <span className="text-sm text-slate-500">
          {status === "pending"      && "Waiting in queue…"}
          {status === "transcribing" && "Transcribing audio with Whisper…"}
          {status === "summarizing"  && "Generating summary with Qwen AI…"}
        </span>
      </div>
      {/* Step pills */}
      <div className="flex gap-1.5">
        {steps.slice(0, 3).map((step, i) => (
          <div
            key={step.key}
            className={`h-1.5 flex-1 rounded-full transition-colors duration-500 ${
              i < currentIdx  ? "bg-violet-500" :
              i === currentIdx ? "bg-violet-400 animate-pulse" :
              "bg-slate-100"
            }`}
          />
        ))}
      </div>
    </div>
  );
}

/* ── Main card ──────────────────────────────────────────── */
export default function MeetingCard({ meeting, onDeleted }) {
  const [showTranscript, setShowTranscript] = useState(false);
  const [deleting, setDeleting] = useState(false);

  const fmt = (iso) =>
    new Date(iso).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });

  const handleDelete = async (e) => {
    e.stopPropagation();
    if (!confirm("Delete this meeting?")) return;
    setDeleting(true);
    try {
      await deleteMeeting(meeting.id);
      onDeleted(meeting.id);
    } catch {
      setDeleting(false);
    }
  };

  const isDone  = meeting.status === "done";
  const isError = meeting.status === "error";
  const inProg  = ["pending","transcribing","summarizing"].includes(meeting.status);

  return (
    <div className="bg-white rounded-2xl border border-slate-100 shadow-sm hover:shadow-md transition-shadow duration-200 overflow-hidden">

      {/* ── Card header ── */}
      <div className="px-5 py-4 flex items-start justify-between gap-3">
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2 mb-1">
            <span className="text-slate-300 text-base">📁</span>
            <p className="font-semibold text-slate-800 text-sm truncate" title={meeting.filename}>
              {meeting.filename}
            </p>
          </div>
          <p className="text-xs text-slate-400 pl-6">{fmt(meeting.created_at)}</p>
        </div>
        <div className="flex items-center gap-2 flex-shrink-0">
          <StatusBadge status={meeting.status} />
          <button
            onClick={handleDelete}
            disabled={deleting}
            title="Delete"
            className="p-1.5 rounded-lg text-slate-300 hover:text-red-400 hover:bg-red-50 transition-colors duration-150"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/>
            </svg>
          </button>
        </div>
      </div>

      {/* ── Error ── */}
      {isError && meeting.error_message && (
        <div className="mx-5 mb-4 flex items-start gap-2 p-3 bg-red-50 border border-red-100 rounded-xl text-red-600 text-sm">
          <span className="flex-shrink-0">⚠️</span>
          <span className="font-mono text-xs break-all">{meeting.error_message}</span>
        </div>
      )}

      {/* ── In-progress ── */}
      {inProg && <ProcessingBar status={meeting.status} />}

      {/* ── Done: full result ── */}
      {isDone && (
        <div className="border-t border-slate-100">

          {/* Summary */}
          {meeting.summary && (
            <div className="px-5 pt-5 pb-4">
              <h4 className="text-xs font-bold tracking-widest uppercase text-slate-400 mb-2 flex items-center gap-1.5">
                <span>📋</span> Summary
              </h4>
              <p className="text-sm text-slate-600 leading-relaxed bg-slate-50 rounded-xl p-4 border border-slate-100">
                {meeting.summary}
              </p>
            </div>
          )}

          {/* Decisions + Actions */}
          <div className="px-5 pb-4 grid sm:grid-cols-2 gap-3">
            <SectionBlock title="Key Decisions" icon="✅" colorClass="bg-indigo-50/60 border border-indigo-100">
              <ItemList items={meeting.key_decisions} variant="decision" />
            </SectionBlock>
            <SectionBlock title="Action Items" icon="📌" colorClass="bg-violet-50/60 border border-violet-100">
              <ItemList items={meeting.action_items} variant="action" />
            </SectionBlock>
          </div>

          {/* Transcript + PDF row */}
          <div className="px-5 pb-5 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4">
            {/* Transcript toggle */}
            {meeting.transcript && (
              <button
                onClick={() => setShowTranscript(v => !v)}
                className="inline-flex items-center gap-1.5 text-xs font-medium text-slate-500 hover:text-violet-600 transition-colors duration-150"
              >
                <svg className={`w-3.5 h-3.5 transition-transform ${showTranscript ? "rotate-180" : ""}`}
                  fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/>
                </svg>
                {showTranscript ? "Hide" : "Show"} full transcript
              </button>
            )}

            {/* PDF download */}
            <button
              onClick={() => downloadPdf(meeting)}
              className="
                inline-flex items-center gap-2 px-4 py-2 rounded-xl
                bg-gradient-to-r from-violet-600 to-indigo-600
                hover:from-violet-700 hover:to-indigo-700
                text-white text-xs font-semibold shadow-sm
                transition-all duration-150 active:scale-95
              "
            >
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414A1 1 0 0121 9.414V19a2 2 0 01-2 2z"/>
              </svg>
              Download PDF
            </button>
          </div>

          {/* Transcript body */}
          {showTranscript && meeting.transcript && (
            <div className="px-5 pb-5">
              <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 text-xs text-slate-500 leading-relaxed whitespace-pre-wrap max-h-56 overflow-y-auto font-mono">
                {meeting.transcript}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
