import { useState, useEffect } from "react";
import { deleteMeeting } from "../api/client";

/* ── Status badge config ──────────────────────────────────── */
const STATUS = {
  pending:      { label: "QUEUED",       bg: "bg-amber-500/20",   text: "text-amber-500",  pulse: "animate-pulse" },
  transcribing: { label: "TRANSCRIBING", bg: "bg-cyan-500/20",    text: "text-accent-cyan",pulse: "animate-pulse" },
  summarizing:  { label: "SUMMARIZING",  bg: "bg-accent-purple/20",text: "text-accent-purple",pulse: "animate-pulse" },
  done:         { label: "DONE",         bg: "bg-emerald-500/20", text: "text-emerald-500",pulse: "" },
  error:        { label: "ERROR",        bg: "bg-red-500/20",     text: "text-red-500",    pulse: "" },
};

/* ── PDF Export ───────────────────────────────────────────── */
function downloadPdf(meeting) {
  const fmt = (iso) => new Date(iso).toLocaleString("en-IN", {
    dateStyle: "long", timeStyle: "short",
  });

  const listHtml = (items, numbered = false) =>
    items.length === 0
      ? "<p style='color:#94a3b8;font-style:italic'>None recorded.</p>"
      : `<ol style='padding-left:1.4em;margin:0;${numbered ? "" : "list-style:none;padding-left:0"}'>
           ${items.map((it, i) => `
             <li style='margin-bottom:8px;display:flex;gap:10px;align-items:flex-start'>
               <span style='background:#7c3aed;color:#fff;border-radius:50%;
                 min-width:22px;height:22px;display:inline-flex;align-items:center;
                 justify-content:center;font-size:11px;font-weight:700;margin-top:1px'>${i+1}</span>
               <span style='flex:1;color:#334155'>${it}</span>
             </li>`).join("")}
         </ol>`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Meeting Summary — ${meeting.filename}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Inter, system-ui, sans-serif; background: #fff; color: #1e293b;
         padding: 48px; max-width: 800px; margin: 0 auto; }
  .header { border-bottom: 3px solid #7c3aed; padding-bottom: 24px; margin-bottom: 32px; }
  .logo   { font-size: 13px; color: #7c3aed; font-weight: 600; letter-spacing:.05em;
            text-transform:uppercase; margin-bottom: 12px; }
  h1      { font-size: 22px; font-weight: 700; color: #1e293b; margin-bottom: 6px; }
  .meta   { font-size: 13px; color: #94a3b8; }
  .section { margin-bottom: 28px; }
  .section-title {
    font-size: 11px; font-weight: 700; letter-spacing: .08em;
    text-transform: uppercase; color: #7c3aed;
    margin-bottom: 10px; padding-bottom: 6px;
    border-bottom: 1px solid #ede9fe;
  }
  .summary-text { font-size: 15px; line-height: 1.7; color: #334155; }
  .transcript-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px;
    padding: 16px; font-size: 13px; line-height: 1.7; color: #64748b;
    white-space: pre-wrap; max-height: none; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0;
    font-size: 11px; color: #cbd5e1; text-align: center; }
  @media print {
    body { padding: 32px; }
    .no-print { display: none; }
  }
</style>
</head>
<body>
  <div class="header">
    <div class="logo">🎙️ Meeting Summarizer</div>
    <h1>${meeting.filename}</h1>
    <div class="meta">${meeting.created_at ? fmt(meeting.created_at) : ""}</div>
  </div>
  <div class="section">
    <div class="section-title">📋 Summary</div>
    <p class="summary-text">${meeting.summary || "No summary available."}</p>
  </div>
  <div class="section">
    <div class="section-title">✅ Key Decisions</div>
    ${listHtml(meeting.key_decisions || [])}
  </div>
  <div class="section">
    <div class="section-title">📌 Action Items</div>
    ${listHtml(meeting.action_items || [], true)}
  </div>
  ${meeting.transcript ? `
  <div class="section">
    <div class="section-title">📄 Full Transcript</div>
    <div class="transcript-box">${meeting.transcript}</div>
  </div>` : ""}
  <div class="footer">Generated by Meeting Summarizer · Powered by Groq</div>
  <script>window.onload = () => { window.print(); }<\/script>
</body>
</html>`;

  const win = window.open("", "_blank");
  win.document.write(html);
  win.document.close();
}

/* ── Sub-components ─────────────────────────────────────── */
function StatusBadge({ status }) {
  const s = STATUS[status] || STATUS.pending;
  return (
    <div className={`px-3 py-1 rounded-[8px] text-[12px] font-bold ${s.bg} ${s.text} ${s.pulse} flex items-center gap-2`}>
      {s.label}
    </div>
  );
}

function ItemList({ items, variant = "decision" }) {
  if (!items || items.length === 0)
    return <p className="text-sm text-gray-500 italic">None recorded.</p>;

  return (
    <ul className="space-y-2 mt-2">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2.5 text-sm text-gray-300">
          <span className={`flex-shrink-0 font-bold ${variant === 'action' ? 'text-accent-cyan' : 'text-accent-purple'}`}>
            {variant === 'action' ? '✓' : '•'}
          </span>
          <span className="leading-[1.8]">{item}</span>
        </li>
      ))}
    </ul>
  );
}

function TranscriptModal({ transcript, onClose }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/70 backdrop-blur-sm animate-slide-up">
      <div className="bg-dark-900 border border-dark-700 rounded-[16px] w-full max-w-[800px] shadow-glow-strong flex flex-col overflow-hidden">
        {/* Header */}
        <div className="flex justify-between items-center p-6 border-b border-dark-700">
          <h3 className="text-xl font-bold text-white">Full Meeting Transcript</h3>
          <button onClick={onClose} className="text-gray-400 hover:text-white transition-colors p-2 rounded-[8px] bg-dark-800 hover:bg-dark-700">
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        {/* Body */}
        <div className="p-6 overflow-y-auto max-h-[60vh] sm:max-h-[70vh]">
          <div className="bg-[#0a0c10] border-l-[3px] border-accent-purple rounded-[8px] p-4 font-mono text-[13px] text-[#00ff88] leading-[1.6] whitespace-pre-wrap">
            {transcript}
          </div>
        </div>
        {/* Footer */}
        <div className="p-6 border-t border-dark-700 flex justify-end gap-3 bg-dark-800/50">
          <button onClick={() => {
            navigator.clipboard.writeText(transcript);
            alert("Copied to clipboard!");
          }} className="px-5 py-2 rounded-[8px] bg-dark-700 text-white font-medium hover:bg-dark-700/80 transition-colors">
            Copy All
          </button>
          <button onClick={onClose} className="px-5 py-2 rounded-[8px] bg-accent-purple text-white font-bold hover:bg-accent-purple/90 transition-colors shadow-glow">
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

/* ── Main card ──────────────────────────────────────────── */
export default function MeetingCard({ meeting, onDeleted, delay = 0 }) {
  const [showModal, setShowModal] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const t = setTimeout(() => setMounted(true), delay);
    return () => clearTimeout(t);
  }, [delay]);

  const fmt = (iso) =>
    new Date(iso).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });

  const handleDelete = async (e) => {
    e.stopPropagation();
    if (!confirm("Delete this meeting?")) return;
    setDeleting(true);
    try {
      await deleteMeeting(meeting.id);
      onDeleted(meeting.id);
    } catch {
      setDeleting(false);
    }
  };

  const isDone  = meeting.status === "done";
  const isError = meeting.status === "error";
  const inProg  = ["pending","transcribing","summarizing"].includes(meeting.status);

  if (!mounted) return null;

  return (
    <>
      <div className="
        bg-dark-800 border border-dark-700 rounded-[12px] p-6 shadow-glow
        relative overflow-hidden group hover:border-accent-purple hover:shadow-glow-strong hover:-translate-y-1 transition-all duration-200 ease-in-out
        animate-slide-up flex flex-col h-full
      ">
        {/* Neon left border gradient */}
        <div className="absolute left-0 top-0 bottom-0 w-[4px] bg-gradient-to-b from-accent-purple to-accent-cyan" />

        {/* ── Card header ── */}
        <div className="flex items-start justify-between gap-3 mb-6">
          <div className="min-w-0">
            <h3 className="font-bold text-white text-[18px] truncate mb-1" title={meeting.filename}>
              {meeting.filename}
            </h3>
            <p className="text-xs text-gray-500">{fmt(meeting.created_at)}</p>
          </div>
          <div className="flex items-center gap-3 flex-shrink-0">
            <StatusBadge status={meeting.status} />
            <button
              onClick={handleDelete}
              disabled={deleting}
              title="Delete"
              className="w-5 h-5 flex items-center justify-center text-gray-500 hover:text-red-500 hover:bg-accent-purple/20 rounded transition-all duration-200 group-hover:opacity-100"
            >
              <svg className="w-4 h-4 transition-transform duration-200 hover:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        {/* ── Error ── */}
        {isError && meeting.error_message && (
          <div className="mt-auto mb-2 p-3 bg-red-500/10 border border-red-500/20 rounded-[8px] text-red-400 text-sm">
            <span className="font-mono text-[13px]">{meeting.error_message}</span>
          </div>
        )}

        {/* ── In-progress visual ── */}
        {inProg && (
          <div className="mt-auto pt-6 border-t border-dark-700">
            <div className="h-1 bg-dark-700 rounded-full overflow-hidden mb-2">
              <div className="h-full bg-gradient-to-r from-accent-cyan to-accent-purple animate-waveform w-1/2 rounded-full" />
            </div>
            <p className="text-xs text-gray-400 font-medium tracking-wide uppercase">
              Processing Audio Data...
            </p>
          </div>
        )}

        {/* ── Done: full result ── */}
        {isDone && (
          <div className="flex flex-col flex-grow">
            {/* Summary */}
            {meeting.summary && (
              <div className="mb-6">
                <h4 className="text-xs font-bold text-accent-purple uppercase tracking-[0.08em] mb-2 border-b border-dark-700 pb-1">
                  Summary
                </h4>
                <p className="text-sm text-gray-300 leading-[1.7] italic">
                  "{meeting.summary}"
                </p>
              </div>
            )}

            {/* Decisions */}
            <div className="mb-6">
              <h4 className="text-xs font-bold text-accent-cyan uppercase tracking-[0.08em] mb-1 border-b border-dark-700 pb-1">
                🎯 Key Decisions
              </h4>
              <ItemList items={meeting.key_decisions} variant="decision" />
            </div>

            {/* Actions */}
            <div className="mb-6 flex-grow">
              <h4 className="text-xs font-bold text-accent-pink uppercase tracking-[0.08em] mb-1 border-b border-dark-700 pb-1">
                ✓ Action Items
              </h4>
              <ItemList items={meeting.action_items} variant="action" />
            </div>

            {/* Actions footer */}
            <div className="flex flex-wrap items-center justify-between gap-3 pt-4 border-t border-dark-700 mt-auto">
              <button
                onClick={() => setShowTranscript(true)}
                disabled={!meeting.transcript}
                className="text-[14px] font-medium text-gray-400 hover:text-white transition-colors disabled:opacity-50"
              >
                [View Transcript]
              </button>

              <button
                onClick={() => downloadPdf(meeting)}
                className="text-[14px] font-medium text-accent-cyan hover:text-white transition-colors"
              >
                [Download PDF]
              </button>
            </div>
          </div>
        )}
      </div>
      
      {showModal && (
        <TranscriptModal transcript={meeting.transcript} onClose={() => setShowModal(false)} />
      )}
    </>
  );
}
